"""Render briefs to email (HTML + plaintext) and Teams Adaptive Card payloads."""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any

from jinja2 import Environment, select_autoescape

from soti_compete.storage import Brief


@dataclass
class RenderedEmail:
    subject: str
    plaintext: str
    html: str


_ENV = Environment(autoescape=select_autoescape(["html", "xml"]), trim_blocks=True, lstrip_blocks=True)


_HTML_TEMPLATE = _ENV.from_string("""\
<!doctype html>
<html><head><meta charset="utf-8"><title>{{ subject }}</title>
<style>
body{font-family:-apple-system,Segoe UI,Helvetica,Arial,sans-serif;color:#222;max-width:760px;margin:0 auto;padding:16px}
.brief{border:1px solid #ddd;border-radius:6px;padding:14px;margin-bottom:14px}
.brief h3{margin:0 0 6px 0}
.meta{color:#666;font-size:13px;margin-bottom:8px}
.scores{font-size:13px;color:#444;background:#f6f7f9;padding:8px;border-radius:4px;margin:8px 0}
.bucket{display:inline-block;padding:2px 8px;border-radius:3px;font-size:12px;font-weight:600;color:#fff;margin-right:8px}
.P0{background:#c0392b}.P1{background:#d68910}.P2{background:#7d8a96}
.gap{font-size:13px;background:#fbfbfd;border-left:3px solid #4a90e2;padding:8px 10px;margin:8px 0}
.sources{font-size:12px;color:#555}
.sources a{color:#3a6ea5}
.stub{color:#8a6d3b;font-style:italic;font-size:12px}
</style></head><body>
<h2>{{ heading }}</h2>
<p class="meta">{{ subheading }}</p>
{% for b in briefs %}
<div class="brief">
  <h3><span class="bucket {{ b.bucket }}">{{ b.bucket }}</span>{{ b.title }}</h3>
  <div class="meta">
    {{ b.competitor_id or "n/a" }} &middot; {{ b.news_type or "n/a" }} &middot; {{ b.response_type }}
    &middot; final: {{ "%.2f"|format(b.final_score) }}
  </div>
  {% if b.summary %}<p>{{ b.summary }}</p>{% endif %}
  <div class="scores">
    raw {{ "%.2f"|format(b.raw_score) }} ×
    recency {{ "%.2f"|format(b.recency_multiplier) }} ×
    confidence {{ "%.2f"|format(b.confidence_multiplier) }}
    &nbsp;|&nbsp;
    {% for k, v in b.dimensions.items() %}{{ k }}={{ v }}{% if not loop.last %}, {% endif %}{% endfor %}
  </div>
  {% if b.gap_analysis %}
  <div class="gap">
    <strong>Gap analysis</strong><br>
    {% if b.gap_analysis.soti_today %}<div>SOTI today: {{ b.gap_analysis.soti_today }}</div>{% endif %}
    {% if b.gap_analysis.roadmap %}<div class="stub">Roadmap: {{ b.gap_analysis.roadmap }}</div>{% endif %}
    {% if b.gap_analysis.others %}<div>Other competitors: {{ b.gap_analysis.others }}</div>{% endif %}
  </div>
  {% endif %}
  {% if b.sources %}
  <div class="sources">
    Sources:
    {% for s in b.sources %}<a href="{{ s.url }}">{{ s.domain or s.url }}</a>{% if not loop.last %} &middot; {% endif %}{% endfor %}
  </div>
  {% endif %}
</div>
{% endfor %}
<p class="meta">Generated by SOTI Compete.</p>
</body></html>
""")

_TEXT_TEMPLATE = _ENV.from_string("""\
{{ heading }}
{{ subheading }}

{% for b in briefs %}
[{{ b.bucket }}] {{ b.title }}
  competitor: {{ b.competitor_id or "n/a" }}  news: {{ b.news_type or "n/a" }}  response: {{ b.response_type }}
  final={{ "%.2f"|format(b.final_score) }} = raw {{ "%.2f"|format(b.raw_score) }} x recency {{ "%.2f"|format(b.recency_multiplier) }} x confidence {{ "%.2f"|format(b.confidence_multiplier) }}
  dimensions: {% for k, v in b.dimensions.items() %}{{ k }}={{ v }}{% if not loop.last %}, {% endif %}{% endfor %}

  {% if b.summary %}{{ b.summary }}{% endif %}
  {% if b.gap_analysis.soti_today %}SOTI today: {{ b.gap_analysis.soti_today }}{% endif %}
  {% if b.gap_analysis.roadmap %}Roadmap: {{ b.gap_analysis.roadmap }}{% endif %}
  {% if b.gap_analysis.others %}Others: {{ b.gap_analysis.others }}{% endif %}
  {% if b.sources %}sources: {% for s in b.sources %}{{ s.url }}{% if not loop.last %} | {% endif %}{% endfor %}{% endif %}

{% endfor %}
-- SOTI Compete
""")


def render_email(
    briefs: Sequence[Brief],
    *,
    subject: str,
    heading: str | None = None,
    subheading: str = "",
) -> RenderedEmail:
    heading = heading or subject
    ctx = {"briefs": briefs, "subject": subject, "heading": heading, "subheading": subheading}
    return RenderedEmail(
        subject=subject,
        plaintext=_TEXT_TEMPLATE.render(**ctx),
        html=_HTML_TEMPLATE.render(**ctx),
    )


def render_teams_card(brief: Brief, *, title_prefix: str = "P0 Competitive Alert") -> dict[str, Any]:
    facts = [
        {"title": "Competitor", "value": brief.competitor_id or "n/a"},
        {"title": "News type", "value": brief.news_type or "n/a"},
        {"title": "Response", "value": brief.response_type},
        {"title": "Final score", "value": f"{brief.final_score:.2f}"},
        {
            "title": "Multipliers",
            "value": f"raw {brief.raw_score:.2f} × recency {brief.recency_multiplier:.2f} × confidence {brief.confidence_multiplier:.2f}",
        },
    ]
    if brief.gap_analysis.get("soti_today"):
        facts.append({"title": "SOTI today", "value": brief.gap_analysis["soti_today"]})
    if brief.gap_analysis.get("roadmap"):
        facts.append({"title": "Roadmap", "value": brief.gap_analysis["roadmap"]})

    body = [
        {
            "type": "TextBlock",
            "text": f"{title_prefix}: {brief.title}",
            "weight": "Bolder",
            "size": "Medium",
            "wrap": True,
        },
        {
            "type": "TextBlock",
            "text": f"Bucket {brief.bucket}",
            "isSubtle": True,
            "spacing": "None",
        },
        {"type": "FactSet", "facts": facts},
    ]
    if brief.summary:
        body.append({"type": "TextBlock", "text": brief.summary, "wrap": True})

    actions = []
    for s in brief.sources[:4]:
        url = s.get("url")
        if url:
            actions.append({"type": "Action.OpenUrl", "title": s.get("domain") or "Source", "url": url})

    return {
        "type": "message",
        "attachments": [
            {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "type": "AdaptiveCard",
                    "version": "1.4",
                    "body": body,
                    "actions": actions,
                },
            }
        ],
    }


__all__ = ["RenderedEmail", "render_email", "render_teams_card"]
